# OS-Specific Setup
[arch]
localhost

# App Installation/Configuration
[ghostty]
localhost

[hyprland]
localhost

[hyprlock]
localhost

[kanshi]
localhost

[mako]
localhost

[neovim]
localhost

[rofi]
localhost

[starship]
localhost

[tmux]
localhost

[waybar]
localhost
