- name: Install Arch AUR packages
  kewlfft.aur.aur:
    name: neovim-git
    use: paru
    state: present
  become: yes
  become_user: aur_builder
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Apply Neovim config
  ansible.builtin.shell: 'stow --target=${HOME} neovim'
  args:
    chdir: '{{ playbook_dir }}/../dotfiles'
  become: yes
  become_user: '{{ user }}'
