$bg_dim = rgb(f6f4f4)
$bg = rgb(f0edec)
$bg_raised = rgb(cfc1ba)
$surface = rgb(b3aba8)
$surface_hi = rgb(999798)
$overlay = rgb(808487)

$fg_hi = rgb(222a2f)
$fg = rgb(2c363c)
$fg_dim = rgb(3e4a52)
$fg_faint = rgb(4f5e68)

$cursor = rgb(2c363c)
$sel_bg = rgb(cfc1ba)
$sel_fg = rgb(2c363c)
$border = rgb(b3aba8)

$red = rgb(a8334c)
$orange = rgb(944927)
$yellow = rgb(944927)
$green = rgb(4f6c31)
$cyan = rgb(3b8992)
$blue = rgb(286486)
$magenta = rgb(88507d)
$gray = rgb(cfc1ba)

$red_br = rgb(94253e)
$orange_br = rgb(803d1c)
$yellow_br = rgb(803d1c)
$green_br = rgb(3f5a22)
$cyan_br = rgb(2b747c)
$blue_br = rgb(1d5573)
$magenta_br = rgb(7b3b70)
$gray_br = rgb(4f5e68)
