background-color=#f6f4f4
text-color=#2c363c
border-color=#b3aba8
progress-color=over #286486

[urgency=low]
border-color=#cfc1ba
text-color=#4f5e68

[urgency=normal]
border-color=#944927

[urgency=critical]
border-color=#a8334c
text-color=#94253e
default-timeout=0
