#! /bin/sh

#########
# Input #
#########

# Start keybindings if they haven't already been started
pgrep -x sxhkd > /dev/null || sxhkd &

# Enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

##############
# Appearance #
##############

# Set number of desktops and their labels
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Show status bar
killall polybar ; polybar main &

# Improve launching time for firefox
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

# Set wallpaper
~/.fehbg &

# Colors (from Aquarium vim)
bspc config normal_border_color     "#1a1a24"
bspc config active_border_color     "#3d4059"
bspc config focused_border_color    "#63718b"
bspc config presel_border_color     "#ebb9b9"

# Borders and gaps
bspc config border_width            2%
bspc config window_gap              8%

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Show shadows/blurring/transitions
pgrep -x picom > /dev/null || picom &
