#! /bin/sh

# Start keybindings if they haven't already been started
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d          

killall polybar ; polybar main &

# Set wallpaper
~/.fehbg &

# Colors (from Aquarium)
bspc config normal_border_color		"#1a1a24"
bspc config active_border_color 	"#3d4059"
bspc config focused_border_color 	"#63718b"
bspc config presel_border_color 	"#ebb9b9"

# Visuals
bspc config border_width		2
bspc config window_gap			15

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true

# Enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
