- name: Install Arch packages
  community.general.pacman:
    name: rofi
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Apply Rofi config
  ansible.builtin.shell: 'stow --target=${HOME} rofi'
  args:
    chdir: '{{ playbook_dir }}/../dotfiles'
  become: true
  become_user: '{{ user }}'
