background-color=#1d2021
text-color=#ebdbb2
border-color=#504945
progress-color=over #458588

[urgency=low]
border-color=#3c3836
text-color=#a89984

[urgency=normal]
border-color=#d65d0e

[urgency=critical]
border-color=#cc241d
text-color=#fb4934
default-timeout=0
