- name: Install Arch packages
  community.general.pacman:
    name:
      - brightnessctl
      - niri
      - playerctl
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Apply Niri config
  ansible.builtin.shell: 'stow --target=${HOME} niri'
  args:
    chdir: '{{ playbook_dir }}/../dotfiles'
  become: true
  become_user: '{{ user }}'
