$bg_dim = rgb(2c2e2e)
$bg = rgb(3f3f3f)
$bg_raised = rgb(434443)
$surface = rgb(464646)
$surface_hi = rgb(5b605e)
$overlay = rgb(5d6262)

$fg_hi = rgb(dfe4cf)
$fg = rgb(dcdccc)
$fg_dim = rgb(9f9f9f)
$fg_faint = rgb(8f8f8f)

$cursor = rgb(8faf9f)
$sel_bg = rgb(284f28)
$sel_fg = rgb(ffffe0)
$border = rgb(5b605e)

$red = rgb(cc9393)
$orange = rgb(dfaf8f)
$yellow = rgb(f0dfaf)
$green = rgb(7f9f7f)
$cyan = rgb(8cd0d3)
$blue = rgb(8c8cbc)
$magenta = rgb(bc8cbc)
$gray = rgb(8f8f8f)

$red_br = rgb(dca3a3)
$orange_br = rgb(ffcfaf)
$yellow_br = rgb(efef8f)
$green_br = rgb(9ece9e)
$cyan_br = rgb(71d3b4)
$blue_br = rgb(9fafaf)
$magenta_br = rgb(bc8cbc)
$gray_br = rgb(9f9f9f)
