background-color=#2c2e2e
text-color=#dcdccc
border-color=#5b605e
progress-color=over #8c8cbc

[urgency=low]
border-color=#434443
text-color=#9f9f9f

[urgency=normal]
border-color=#dfaf8f

[urgency=critical]
border-color=#cc9393
text-color=#dca3a3
default-timeout=0
