- name: Install Arch packages
  community.general.pacman:
    name: fuzzel
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Apply Fuzzel config
  ansible.builtin.shell: 'stow --target=${HOME} fuzzel'
  args:
    chdir: '{{ playbook_dir }}/../dotfiles'
  become: true
  become_user: '{{ user }}'
