---
- name: Apply Dotfiles
  hosts: targets
  remote_user: root
  gather_facts: true
  roles: # Uncomment the apps you want to install/configure
    - common
    - fuzzel
    - ghostty
    - niri
    - neovim
    - tmux
