$bg_dim = rgb(110f0e)
$bg = rgb(1c1917)
$bg_raised = rgb(403833)
$surface = rgb(504b48)
$surface_hi = rgb(5e5d5c)
$overlay = rgb(6d6e6f)

$fg_hi = rgb(c4cacf)
$fg = rgb(b4bdc3)
$fg_dim = rgb(9ea6ac)
$fg_faint = rgb(888f94)

$cursor = rgb(c4cacf)
$sel_bg = rgb(403833)
$sel_fg = rgb(b4bdc3)
$border = rgb(504b48)

$red = rgb(de6e7c)
$orange = rgb(b77e64)
$yellow = rgb(b77e64)
$green = rgb(819b69)
$cyan = rgb(66a5ad)
$blue = rgb(6099c0)
$magenta = rgb(b279a7)
$gray = rgb(403833)

$red_br = rgb(e8838f)
$orange_br = rgb(d68c67)
$yellow_br = rgb(d68c67)
$green_br = rgb(8bae68)
$cyan_br = rgb(65b8c1)
$blue_br = rgb(61abda)
$magenta_br = rgb(cf86c1)
$gray_br = rgb(888f94)
