background-color=#110f0e
text-color=#b4bdc3
border-color=#504b48
progress-color=over #6099c0

[urgency=low]
border-color=#403833
text-color=#888f94

[urgency=normal]
border-color=#b77e64

[urgency=critical]
border-color=#de6e7c
text-color=#e8838f
default-timeout=0
