source = ~/.config/colors/current/hyprlock.conf

$font = Terminess Nerd Font

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = clunk, 0.25, 1, 0.5, 1
    animation = fadeIn, 1, 2, clunk
    animation = fadeOut, 1, 2, clunk
    animation = inputFieldDots, 1, 1, clunk
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

label {
    monitor =
    text = [ SYSTEM LOCKED ]
    color = $orange_br
    font_size = 16
    font_family = $font

    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $fg
    font_size = 96
    font_family = $font

    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = $fg_faint
    font_size = 15
    font_family = $font

    position = 0, 50
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 46
    outline_thickness = 3
    rounding = 0

    inner_color = $bg
    outer_color = $orange_br
    check_color = $yellow_br
    fail_color = $red_br
    font_color = $fg

    font_family = $font
    placeholder_text = ENTER PASSCODE
    check_text = AUTHENTICATING
    fail_text = $FAIL

    dots_text_format = *
    dots_size = 0.25
    dots_spacing = 0.4
    fade_on_empty = false

    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = [ OPERATOR: $USER ]
    color = $overlay
    font_size = 12
    font_family = $font

    position = 0, -100
    halign = center
    valign = center
}
