background = #000108
foreground = #EEEAE8
cursor-color = #A19F98
selection-background = #DFD9D5
selection-foreground = #000108

palette = 0=#000108
palette = 1=#01354A
palette = 2=#535448
palette = 3=#066E74
palette = 4=#917D73
palette = 5=#78999E
palette = 6=#CFC4BC
palette = 7=#DFD9D5
palette = 8=#9C9895
palette = 9=#01354A
palette = 10=#535448
palette = 11=#066E74
palette = 12=#917D73
palette = 13=#78999E
palette = 14=#CFC4BC
palette = 15=#DFD9D5
