background = #111112
foreground = #F9F6F8
cursor-color = #ACADA0
selection-background = #EEEAEC
selection-foreground = #111112

palette = 0=#393A3A
palette = 1=#612C3B
palette = 2=#606448
palette = 3=#8D7D84
palette = 4=#DC8742
palette = 5=#A2B08B
palette = 6=#EDE6EA
palette = 7=#EEEAEC
palette = 8=#A6A4A5
palette = 9=#612C3B
palette = 10=#606448
palette = 11=#8D7D84
palette = 12=#DC8742
palette = 13=#A2B08B
palette = 14=#EDE6EA
palette = 15=#EEEAEC
