$bg_dim = rgb(f9f5d7)
$bg = rgb(fbf1c7)
$bg_raised = rgb(ebdbb2)
$surface = rgb(d5c4a1)
$surface_hi = rgb(bdae93)
$overlay = rgb(a89984)

$fg_hi = rgb(282828)
$fg = rgb(3c3836)
$fg_dim = rgb(504945)
$fg_faint = rgb(665c54)

$cursor = rgb(d65d0e)
$sel_bg = rgb(d5c4a1)
$sel_fg = rgb(3c3836)
$border = rgb(bdae93)

$red = rgb(cc241d)
$orange = rgb(d65d0e)
$yellow = rgb(d79921)
$green = rgb(98971a)
$cyan = rgb(689d6a)
$blue = rgb(458588)
$magenta = rgb(b16286)
$gray = rgb(7c6f64)

$red_br = rgb(9d0006)
$orange_br = rgb(af3a03)
$yellow_br = rgb(b57614)
$green_br = rgb(79740e)
$cyan_br = rgb(427b58)
$blue_br = rgb(076678)
$magenta_br = rgb(8f3f71)
$gray_br = rgb(928374)
